### ISSUE TITLE
After upgrading to 0.1.4 codeclimate reports seem to break

### ISSUE THREAD

**Issue by jcoyne** [codeclimate-community/simplecov_json_formatter#4]
It started saying:

```
Error: could not find coverage info for source files
Usage:
  cc-test-reporter after-build [flags]
```
https://app.circleci.com/pipelines/github/sul-dlss/sdr-client/250/workflows/0dd4acf9-aeb3-48ec-9610-ed09a02350a9/jobs/233

I've fixed my build by downgrading https://github.com/sul-dlss/sdr-client/pull/179

**Comment by fede-moya** [comment]
@jcoyne sorry about that. A fix https://github.com/codeclimate/test-reporter/pull/488 will be release tomorrow morning.

**Comment by jcoyne** [comment]
Yes, things are working again.  Thank you. I appreciate your prompt communication about what was going on.
