### ISSUE TITLE
No git tag / release for 0.1.4

### ISSUE THREAD

**Issue by Segaja** [codeclimate-community/simplecov_json_formatter#5]
Hi,

according to https://rubygems.org/gems/simplecov_json_formatter the current version is `0.1.4`, but when I look at https://github.com/codeclimate-community/simplecov_json_formatter/tags the current version is `0.1.2`. 

Many linux distributions (like Arch Linux in my case) use the git tags as reference to download the source code and build the package from it.

While trying to package this gem I found out the tag is missing.

Can you please create it?

**Comment by fede-moya** [comment]
Done!, sorry for the inconvenience.
